config/routes.rb
PushServer::Application.routes.draw do
  match '/auth/:provider/callback', to: 'sessions#create', via: [:get, :post]

  resources :users

  resources :devices do
    resources :messages
    post 'send_message', on: :member
  end

  resources :clients do
    resources :messages
  end

  get '/messages' => 'messages#list'
  get '/logout'   => 'sessions#destroy'

  root to: 'users#index'

  namespace :api do
    get  'sender_id', to: 'devices#sender_id'
    post 'messages', to: 'messages#send_message'
    post 'devices/register'
    post 'devices/:device_name/messages', to: 'devices#send_message'
  end
end

app/models/device.rb
class Device < ActiveRecord::Base
  # validation checks
  validates :name, :presence => true, uniqueness: { scope: :user_id }
  validates :device_type, :presence => true

  has_many :messages
  belongs_to :user

  before_create :generate_registration_token

  # Checks if this device has a push_id associated with it.
  def registered?
    !push_id.nil?
  end

  # Generates a new unique registration token for device.
  def generate_registration_token
    candidate_token = nil

    while candidate_token.nil?
      candidate_token = SecureRandom.hex(3).upcase
      candidate_token = nil unless Device.find_by(registration_token: candidate_token).nil?
    end

    self.registration_token = candidate_token
  end

  # Adds push identifier to device based on supplied registration token.
  def self.register(registration_token, push_id)
    device = Device.find_by(registration_token: registration_token.upcase)

    raise Exceptions::DeviceNotFound unless device

    device.push_id = push_id
    device.registration_token = nil # Let's prevent repeated use of registration token.

    device.save
  end
end

app/controllers/api/devices_controller.rb
class Api::DevicesController < ApiController
  # GET /sender_id
  def sender_id
    render json: { status: 'success', sender_id: COURIER_CONFIG[:gcm_project_number] }
  end

  # POST /register
  def register
    require_params [:token, :push_id]

    begin
      Device.register(params[:token], params[:push_id])
    rescue Exceptions::DeviceNotFound => e
      render json: { status: 'failure', error_code: e.error_code, description: 'Could not find a device with the supplied token.' } and return
    end

    render json: { status: 'success', description: 'Device push identifier has been registered.' }
  end

  # POST /:device_name/messages
  def send_message
    require_params [:message, :access_token]

    begin
      Message.send_message(params[:message], params[:access_token], params[:device_name])
    rescue Exceptions::ClientNotFound => e
      render json: { status: 'failure', error_code: e.error_code, description: 'Could not authenticate access token.' } and return
    rescue Exceptions::DeviceNotFound => e
      render json: { status: 'failure', error_code: e.error_code, description: 'Could not find a device with the supplied name.' } and return
    end

    render json: { status: 'success', description: 'Message has been pushed to device.' }
  end
end

app/controllers/devices_controller.rb
class DevicesController < ApplicationController
  # GET /devices
  def index
    @devices = current_user.devices
  end

  # GET /devices/new
  def new
    @device = current_user.devices.new(device_type: 'android')
  end

  # POST /devices
  def create
    @device = current_user.devices.new(device_params)

    if @device.save
      redirect_to device_url(@device)
    else
      render :new
    end
  end

  # GET /devices/:id
  def show
    @device = Device.find(params[:id])

    unless @device
      # TODO: Render a 404 unless the device exists.
      #render :404
      #return
    end

    @host = request.host
    @port = request.port

    render :show_unready unless @device.registered?
  end

  # POST /devices/:id/send_message
  def send_message
    device = Device.find(params[:id])

    current_user.default_client.send_message(params[:message], device)

    flash[:notice] = 'Your message has been successfully pushed to the device.'
    redirect_to device_url(device)
  end

  private

  def device_params
    params[:device][:device_type] = 'android'
    params[:device].permit(:name, :device_type)
  end
end

app/views/devices/index.html.erb
<table class='table'>
  <thead>
  <tr>
    <th>Name</th>
    <th>Registered?</th>
    <th>Links</th>
  </tr>
  </thead>
  <tbody>
  <% @devices.each do |device| %>
    <tr>
      <td><%= device.name %></td>
      <td><%= device.registered? ? 'Yes' : 'No' %></td>
      <td>
        <%= link_to 'More Info', device_url(device) %>
        <%= link_to 'Messages pushed', device_messages_url(device) %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

<div>
  <%= link_to 'Add a new device', new_device_url %>
</div>

app/views/devices/new.html.erb
<%= form_for(@device, html: { class: 'form-horizontal' }) do |f| %>
  <div class='form-group'>
    <%= f.label(:name, nil, class: 'col-lg-2 control-label') %>
    <div class='col-lg-10'>
      <%= f.text_field(:name, class: 'form-control', placeholder: 'Device Name (no spaces)') %>
    </div>
  </div>

  <div class='form-group'>
    <%= f.label(:device_type, nil, class: 'col-lg-2 control-label') %>
    <div class='col-lg-10'>
      <%= f.select(:device_type, options_for_select(%w(android ios), 'android'), {}, class: 'form-control') %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-offset-2 col-lg-10">
      <button type="submit" class="btn btn-default">Add Device</button>
    </div>
  </div>
<% end %>

app/views/devices/show.html.erb
<p>Your <%= @device.device_type %> device is ready to receive messages from this server.</p>

<dl class="dl-horizontal">
  <dt>GCM Registration ID</dt>
  <dd><code class='gcm-registration-id'><%= @device.push_id %></code></dd>
</dl>

<legend>Send a test message</legend>

<p>You can try sending a test message to this device. Type in something below, and push send. You should receive the
  message on your phone momentarily.</p>

<%= form_tag(send_message_device_url(@device), role: 'form') do %>
  <div class='form-group'>
    <%= label_tag(:message, nil) %>
    <%= text_area_tag(:message, nil, placeholder: 'Type in text to send to your device.', class: 'form-control') %>
  </div>

  <%= button_tag('Push to device', class: 'btn btn-default') %>
<% end %>

<br/><legend>Messages Sent</legend>

<%= link_to 'Messages pushed to this device', device_messages_url(@device) %>

app/views/devices/show_unready.html.erb
<p>
  Please enter the following values into the Courier application, running on your mobile device, to register it
  with this message server.
</p>

<dl class="dl-horizontal">
  <dt>Host</dt>
  <dd><%= @host %></dd>
  <dt>Port</dt>
  <dd><%= @port %></dd>
  <dt>Token</dt>
  <dd><code><%= @device.registration_token %></code></dd>
</dl>