config/routes.rb
PushServer::Application.routes.draw do
  match '/auth/:provider/callback', to: 'sessions#create', via: [:get, :post]

  resources :users

  resources :devices do
    resources :messages
    post 'send_message', on: :member
  end

  resources :clients do
    resources :messages
  end

  get '/messages' => 'messages#list'
  get '/logout'   => 'sessions#destroy'

  root to: 'users#index'

  namespace :api do
    get  'sender_id', to: 'devices#sender_id'
    post 'messages', to: 'messages#send_message'
    post 'devices/register'
    post 'devices/:device_name/messages', to: 'devices#send_message'
  end
end

app/models/client.rb
class Client < ActiveRecord::Base
  belongs_to :user
  has_many :messages

  validates :name, uniqueness: { scope: :user_id }
  validates_format_of :name, with: /\A[A-Za-z\d_-]+\z/

  before_create :generate_access_token

  def generate_access_token
    candidate_token = nil

    while candidate_token.nil?
      candidate_token = SecureRandom.urlsafe_base64
      candidate_token = nil unless Client.find_by(access_token: candidate_token).nil?
    end

    self.access_token = candidate_token
  end

  def send_message(message, device)
    Message.send_message(message, self.access_token, device.name)
  end
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  # GET /clients
  def index
    @clients = current_user.clients
  end

  # GET /clients/new
  def new
    @client = current_user.clients.new
  end

  # POST /clients
  def create
    @client = Client.new(client_params)
    @client.user = current_user

    if @client.save
      redirect_to clients_url
    else
      render :new
    end
  end

  private

  def client_params
    params.require(:client).permit(:name)
  end
end

app/views/clients/index.html.erb
<table class='table'>
  <thead>
  <tr>
    <th>Name</th>
    <th>Access Token</th>
    <th>Links</th>
  </tr>
  </thead>
  <tbody>
  <% @clients.each do |client| %>
    <tr>
      <td><%= client.name %></td>
      <td><code><%= client.access_token %></code></td>
      <td>
        <%= link_to 'Messages pushed', client_messages_url(client) %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

<div>
  <%= link_to 'Add a new client', new_client_url %>
</div>

app/views/clients/new.html.erb
<%= form_for(@client, html: { class: 'form-horizontal' }) do |f| %>
  <!-- TODO: Show errors properly when they occur. Right now it looks pretty stupid. -->
  <% @client.errors.full_messages.each do |message| %>
    <%= message %><br/>
  <% end %>

  <div class='form-group'>
    <%= f.label(:name, nil, class: 'col-lg-2 control-label') %>
    <div class='col-lg-10'>
      <%= f.text_field(:name, class: 'form-control', placeholder: 'Client Name [ A-Z a-z _ - ]') %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-offset-2 col-lg-10">
      <button type="submit" class="btn btn-default">Create Client</button>
    </div>
  </div>
<% end %>