config/routes.rb
PushServer::Application.routes.draw do
  match '/auth/:provider/callback', to: 'sessions#create', via: [:get, :post]

  resources :users

  resources :devices do
    resources :messages
    post 'send_message', on: :member
  end

  resources :clients do
    resources :messages
  end

  get '/messages' => 'messages#list'
  get '/logout'   => 'sessions#destroy'

  root to: 'users#index'

  namespace :api do
    get  'sender_id', to: 'devices#sender_id'
    post 'messages', to: 'messages#send_message'
    post 'devices/register'
    post 'devices/:device_name/messages', to: 'devices#send_message'
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><%= content_for?(:title) ? yield(:title) : 'Courier' %></title>

  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag 'application', :media => 'all' %>
  <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>
  <%= javascript_include_tag 'application' %>
</head>
<body>

<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <% if current_user %>
      <button class="navbar-toggle" type="button" data-toggle="collapse" data-target="#bs-navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <% end %>

      <%= link_to('Courier Server', root_url, class: 'navbar-brand') %>
    </div>

    <% if current_user %>
    <div class="collapse navbar-collapse" id="bs-navbar-collapse">
      <ul class="nav navbar-nav">
        <li><%= link_to 'Devices', devices_url %></li>
        <li><%= link_to 'Clients', clients_url %></li>
        <li><%= link_to 'Messages', '/messages' %></li>
        <li><%= link_to 'Logout', '/logout' %></li>
      </ul>
    </div>
    <% end %>
  </div>
</nav>

<div class="container">
  <div class="span12">
    <%= yield %>
  </div>
</div>
<!-- /container -->

<div id="footer-container">
  <div class="container">
    <div class="span12">
      <footer>
        <a href="https://github.com/mobmewireless/courier_server">Courier Server</a> &mdash; Built with love, by the folks at <a href="https://mobme.in/">MobME Wireless</a>.
      </footer>
    </div>
  </div>
</div>

</body>
</html>